config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  resources :locations do
    resources :stories
  end

  resources :stories do
    resources :comments
  end

  resources :stories, only: [ :new, :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story

  validates :body, presence: true
  validates :body, length: { in: 10..255 }
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :stories, dependent: :destroy

  validates :address, presence: true, length: { minimum: 10 }
end

app/models/story.rb
class Story < ApplicationRecord
  has_rich_text :body
  has_many :comments, dependent: :destroy
  belongs_to :location

  validates :address, presence: true, length: { minimum: 10 }
  validates :body, presence: true

  before_validation :set_location

  def set_location
    location = Location.find_by(address: self.address)

    if location
      self.location = location
    else
      self.location = Location.create(address: self.address)
    end
  end
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
    include CrudHelper
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_story, only: %i[ create update destroy ]
  before_action :set_comment, only: %i[ update destroy ]

  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @story.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to story_path(@story), notice: t(".created") }
        format.json { render "stories/show", status: :created, location: @comment }
      else
        @comments = @story.comments.order(created_at: :desc)
        format.html { render "stories/show", status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @story, notice: t(".updated") }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to @story, notice: t(".destroyed") }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_story
    @story = Story.find(params[:story_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :story_id)
  end
end

app/controllers/concerns/crud_helper.rb
module CrudHelper
  extend ActiveSupport::Concern

  private

  def update_record(record, params, redirect_url)
    respond_to do |format|
      if record.update(params)
        format.html { redirect_to redirect_url, notice: t("helpers.crud.update_success") }
        format.json { render :show, status: :ok, location: record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: record.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
    @stories = @location.stories
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: t(".created") }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    update_record(@location, location_params, location_url(@location))
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy!

    respond_to do |format|
      format.html { redirect_to locations_url, notice: t(".destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:address)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show edit update destroy ]
  before_action :set_location, only: %i[ show new ]

  # GET /stories or /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1 or /stories/1.json
  def show
    @comments = @story.comments.order(created_at: :desc)
    @comment = @story.comments.build
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to location_story_path(@story.location, @story), notice: t(".created") }
        format.json { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    update_record(@story, story_params, story_url(@story))
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy!

    respond_to do |format|
      format.html { redirect_to stories_url, notice: t(".destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    def set_location
      @location = Location.find_by(id: params[:location_id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:address, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def localized_time(time, format: "%d.%m.%Y %H:%M")
    return nil if time.nil?
    I18n.with_locale(I18n.locale) { I18n.l(time, format: format) }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<li class="list-group-item", id=<%= dom_id comment %>>
  <small class="text-body-secondary">
    <small class="fst-italic"><%= localized_time(comment.created_at) %> -</small> 
    <small class="fs-6"><%= comment.body %></small>
  </small>
</li>

app/views/comments/_form.html.erb
<%= form_with(model: [@story, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <div id="error_explanation">
        <h4>
          <%= t('comments.form.prohibited') %>:
        </h4>
        <ul>
          <% @comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="w-100">
    <div data-mdb-input-init class="form-outline">
      <%= form.label :body, class: 'form-label', for: 'textAreaExample' %>
      <%= form.text_area :body, class: 'form-control', id: 'textAreaExample', rows: '4' %>
    </div>
    <div class="d-flex justify-content-between mt-3">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1><%= t(".edit_comment") %></h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to t('.show'), @comment %> |
  <%= link_to t('.back_comments'), comments_path %>
</div>

app/views/comments/index.html.erb
<div class='comments'>
  <h3>
    <%= t(".comments_list") %>
  </h3>
  <ul class="list-group">
    <%= render @comments %>
  </ul>
</div>

app/views/comments/new.html.erb
<div class="container my-2 py-2 text-body">
  <div class="row d-flex">
    <div class="card">
      <div class="card-body p-4">
        <h3><%= t("comments.add_comment") %></h3>
        <%= render partial: "comments/form" %>
      </div>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to t('.edit'), edit_story_comment_path(@story, @comment) %> |
  <%= button_to t('.destroy'), story_comment_path(@comment), method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>History</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('logos/favicon.ico')%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">

      <header class="d-flex flex-wrap justify-content-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <%= image_tag("logos/history_logo.webp", size: "60", class: "mx-2") %>
          <span class="fs-4"><%= I18n.t('.header.project_name') %></span>
        </a>
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a href="<%=root_path %>" class="nav-link active" aria-current="page"><%= I18n.t('.header.home_link') %></a>
          </li>
        </ul>
      </header>

      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div style="color: red">
    <h4>
      <%= t('locations.form.prohibited') %>:
    </h4>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :stories_id, style: "display: block" %>
    <%= form.text_field :stories_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <h1>
    <%= location.address %>
  </h1>

  <%= render partial: 'stories' %>
</div>

app/views/locations/_recent.html.erb
<ul>
  <% RecentLocations.new.each do |location| %>
    <li><%= link_to location.address, location %></li>
  <% end %>
</ul>

app/views/locations/_stories.html.erb
<% if @stories.present? %>
  <strong><%= t(".stories") %>:</strong>

  <%= link_to t(".new_story"), location_stories_path(@location) %>

  <ul class="list-group">
    <% @stories.each do |story| %>
      <li class="list-group-item">
        <%= localized_time(story.created_at) %>
        <%= link_to strip_tags(story.body), story_path(story) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/locations/edit.html.erb
<h1><%= t("edit_location") %></h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('locations') %></h1>

<div id="locations">
  <% @locations.each do |location| %>
    <%= render location %>
    <p>
      <%= link_to t('.show'), location %>
    </p>
  <% end %>
</div>

<%= link_to t('.new_location'), new_location_path %>

app/views/locations/new.html.erb
<h1><%= t('.new_location') %> %></h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to t('.back'), locations_path %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to t('.edit'), edit_location_path(@location) %> |
  <%= link_to t('.back'), root_path %>

  <%= button_to t('.destory'), @location, method: :delete %>
</div>

app/views/stories/_form.html.erb
<%= form_with(model: story) do |form| %>
  <% if story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-3">
    <%= form.label :address, style: "display: block", class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="row mb-3">
    <%= form.label :body, style: "display: block", class: "form-label" %>
    <%= form.rich_text_area :body %>
  </div>

  <%= form.submit class: "btn btn-primary mb-3" %>
<% end %>

app/views/stories/_recent.html.erb
<ul>
  <% RecentStories.new.each do |story| %>
    <li><%= link_to story.address, story %></li>
  <% end %>
</ul>

app/views/stories/_story.html.erb
<div id="<%= dom_id story %>">
  <p>
    <strong><%= t('.address') %></strong>
    <%= story.address %>
  </p>

  <p>
    <strong><%= t('.body') %></strong>
    <%= story.body %>
  </p>

</div>

app/views/stories/edit.html.erb
<h1><%= t('.edit')%></h1>

<%= render "form", story: @story, location: @location %>

<br>

<div>
  <%= link_to t('.show'), @story %> |
  <%= link_to t('.back'), location_stories_path(@story) %>
</div>

app/views/stories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('.stories') %></h1>

<%= render partial: 'stories/recent' %>

<%= link_to t('.new_story'), new_story_path %>

app/views/stories/new.html.erb
<h1><%= t('.new_story') %></h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to t('.back'), root_path %>
</div>

app/views/stories/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>
  <%= @story.address %>
</h1>
<p>
  <%= @story.body %>
</p>

<div>
  <%= link_to t('.edit'), edit_story_path(@story) %> |
  <%= link_to t('.back'), location_path(@story.location) %>

  <%= button_to t('.destroy'), story_path(@story), method: :delete %>
</div>

<%= render template: "comments/index" %>
<%= render template: "comments/new" %>

app/views/welcome/index.html.erb
<h1><%= t('.building_history') %></h1>

<%= link_to t(".new_story"), new_story_path %>

<h2><%= t(".recent_locations") %></h2>

<%= render partial: 'locations/recent' %>